/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InsertionSort */

#ifndef _Included_InsertionSort
#define _Included_InsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InsertionSort
 * Method:    insertsort
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_InsertionSort_insertsort
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
